pipeline {
    agent any
    environment {
        JAVA_HOME = "/opt/java/openjdk"
        MAVEN_HOME = "/opt/maven/apache-maven-3.9.2"
        PATH = "${JAVA_HOME}/bin:${MAVEN_HOME}/bin:${PATH}"
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './simple-java-maven-app/jenkins/scripts/deliver.sh'
            }
        }
    }
}
