pipeline {
    agent any
    environment {
        JAVA_HOME = "/opt/java/openjdk"
        MAVEN_HOME = "/opt/maven/apache-maven-3.9.2"
        PATH = "${JAVA_HOME}/bin:${MAVEN_HOME}/bin:${PATH}"
    }
    stages {
        stage("clean Up"){
            steps {
                deleteDir() //Jenkins workspace folder ko clean karega
            }
        }        
        stage("Clone Repo"){
            steps{
                //sh "rm -rf simple-java-maven-app" // Pehle folder delete karega
                sh "git clone https://github.com/jenkins-docs/simple-java-maven-app.git" // Ye directly repo se code pull karega
            }
        }
        //stage("maven path"){
        //    steps{
        //        sh 'which mvn'
        //        sh 'echo $PATH'
        //        sh 'mvn -version'
        //    }
        stage ("build"){
            steps{
                dir('simple-java-maven-app') { // Ye ensure karega ke build isi folder me ho
                    sh 'mvn clean install'  // Maven ka build command run hoga
                } 
            }
        }
        stage ("Test"){
            steps{
                dir('simple-java-maven-app') { // Ye ensure karega ke build isi folder me ho
                    sh 'mvn test'  // Runs Maven tests defined in `pom.xml`
                } 
            }
        }
        stage('Deliver') {
            steps {
                // sh './jenkins/scripts/deliver.sh'
                sh 'jenkins/scripts/deliver.sh'
            }
        }
    }   
}
